### ISSUE TITLE
Rotate layout ignoring floating windows

### ISSUE THREAD

**Issue by nazunga** [KJoke70/i3-tools#1]
I love this tool, but is there a way to include an option to rotate the layout only the tiled windows (excluding the floating windows)?

**Comment by KJoke70** [comment]
Great! I've tested it and it behaves unexpectedly when a floating window is present so I'll consider this a bug. I've now changed the behavior so that rotation and focus will behave as if there was no floating window. If a floating window was focused, the focus will remain on the floating window and only the tiled windows will be rotated. The old behavior can be brought back with the flag `--enable-floating`.

---

Reference: 7b2322bf9ee8a442597347cd440bf0761bebcc60

**Comment by nazunga** [comment]
Thank you, it's perfect...
